
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *default
  database: postgrepvz_test

production:
  <<: *default
  database: postgrepvz_production
  username: postgrepvz
  password: <%= ENV['POSTGREPVZ_DATABASE_PASSWORD'] %>
