# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b394d74fc2fe2d6c61a74f17d4a282766a709f7b03dcf7a4277cf61175c1afa6b12d4f130369fd881cccca5da71692d7ab2dff7c909d9a34f0a9ff8a9bbb032

test:
  secret_key_base: ae11c040fee406d945073dae082d8a588b9c7b01c8bf979f33ac58b2a790052b422db7f9a7b7243629dad45ed272d448dd09bbecae965e111d15da6a7733d0c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
